### ISSUE TITLE
尝试打开黑桃手枪的详细信息界面导致游戏崩溃

### ISSUE THREAD

**Issue by CoronRing** [LesRaisins-Studios/TaC-Test-addon#2]
Game crashes when attempting to open the details page of blackjack revolver with left shift

Raisins: 0.1.4.6
TaC: 0.3.14.2

The game crashed whilst rendering screen
Error: java.lang.NoSuchFieldError: gameplay
![image](https://github.com/LesRaisins-Studios/TaC-Test-addon/assets/89324736/e1b194d0-740b-4aec-adc9-34c62f532a72)

本体crash report报告：

[crash-2024-05-06_15.40.33-client.txt](https://github.com/LesRaisins-Studios/TaC-Test-addon/files/15227310/crash-2024-05-06_15.40.33-client.txt)

**Comment by xjqsh** [comment]
感谢反馈，是tac本体那边改了点配置相关的东西导致引用炸了，连带的还有手雷和闪盾，已修
可以先去拿自动构建的试试
https://github.com/LesRaisins-Studios/TaC-Test-addon/actions/runs/9014588732/artifacts/1487072452
